### ISSUE TITLE
error when doing /awt reset normal

### ISSUE THREAD

**Issue by budies2001** [rypengu23/AutoWorldTools#2]
Hello.

I want to report that I get this error whenever I do /awt reset normal. I am not sure if it is anything I am doing but it is an error in the console and in the game so just a heads up. Thanks. https://pastebin.com/DHAJEmN8

**Comment by rypengu23** [comment]
Thank you for reporting! Even if you haven't installed Discord SRV, there is a bug that it will be loaded, so we will fix it.

**Comment by budies2001** [comment]
I do have discordsrv installed.

**Comment by rypengu23** [comment]
After investigating, I found out that the error occurs when DiscordSRV is included, but the use of DiscordSRV is set to false in Config. Please try to see if it recurs with the fixed version 1.4.

**Comment by budies2001** [comment]
It is fixed. Thanks.
